/**
 * Video catalog + platform metadata for static (GitHub Pages) mode.
 * Generated from backend/services/seed_dataset.py - keep the two in sync.
 */
window.SEED_VIDEOS = [
  {
    "id": "bili-tech-01",
    "title": "【深度测评】iPhone 16 Pro Max 真实体验一个月！续航与影像提升真的巨大吗？",
    "description": "详细对比iPhone 15 Pro Max与16 Pro Max的4K视频录制、散热表现、A18 Pro芯片性能及电池续航测试。",
    "platform": "bilibili",
    "platform_name": "Bilibili (哔哩哔哩)",
    "region": "china",
    "author": "影视飓风 Tim",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    "view_count": "3,420,000",
    "view_count_raw": 3420000,
    "duration": "18:45",
    "publish_date": "2026-09-20",
    "match_score": 98,
    "thumbnail_url": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.bilibili.com/video/BV1iPhone16ProMax",
    "category": "Electronics",
    "keywords": [
      "iphone",
      "iphone 16",
      "apple",
      "smartphone",
      "โทรศัพท์",
      "ไอโฟน",
      "มือถือ",
      "camera",
      "测评"
    ]
  },
  {
    "id": "douyin-tech-02",
    "title": "大疆 DJI Mini 4 Pro 航拍机开箱试飞！新手入门这台够用吗？",
    "description": "开箱最新大疆无人机，展示4K全向避障功能、夜景航拍画质与全景拍摄技巧。",
    "platform": "douyin",
    "platform_name": "Douyin (抖音)",
    "region": "china",
    "author": "科技小杰",
    "author_avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    "view_count": "1,890,000",
    "view_count_raw": 1890000,
    "duration": "03:15",
    "publish_date": "2026-08-15",
    "match_score": 95,
    "thumbnail_url": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.douyin.com/video/7290192831",
    "category": "Electronics",
    "keywords": [
      "dji",
      "drone",
      "mini 4 pro",
      "โดรน",
      "camera",
      "ถ่ายภาพ",
      "航拍"
    ]
  },
  {
    "id": "xhs-beauty-01",
    "title": "花西子/完美日记/Hold Live 热门唇釉大横评！哪只才是黄皮白月光？",
    "description": "高清试色！10款热门国货口红持久度、不掉色测试与显白对比。",
    "platform": "xiaohongshu",
    "platform_name": "Xiaohongshu (小红书)",
    "region": "china",
    "author": "美妆小仙女",
    "author_avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    "view_count": "850,000",
    "view_count_raw": 850000,
    "duration": "05:20",
    "publish_date": "2026-09-01",
    "match_score": 94,
    "thumbnail_url": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.xiaohongshu.com/discovery/item/65819a",
    "category": "Beauty",
    "keywords": [
      "lipstick",
      "lip glow",
      "holdlive",
      "cosmetics",
      "ลิปสติก",
      "เครื่องสำอาง",
      "แต่งหน้า",
      "口红",
      "试色"
    ]
  },
  {
    "id": "bili-home-01",
    "title": "【家电测评】石头 Roborock S8 MaxV Ultra 扫地机器人能彻底解放双手吗？",
    "description": "实测机械臂贴边清扫、高温热水洗拖布、AI识别宠物粪便与障碍物避障测试。",
    "platform": "bilibili",
    "platform_name": "Bilibili (哔哩哔哩)",
    "region": "china",
    "author": "先看评测",
    "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    "view_count": "2,150,000",
    "view_count_raw": 2150000,
    "duration": "15:10",
    "publish_date": "2026-08-28",
    "match_score": 93,
    "thumbnail_url": "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.bilibili.com/video/BV1RoborockS8",
    "category": "Home",
    "keywords": [
      "roborock",
      "vacuum",
      "robot vacuum",
      "หุ่นยนต์ดูดฝุ่น",
      "เครื่องใช้ไฟฟ้า",
      "扫地机器人"
    ]
  },
  {
    "id": "douyin-shoes-01",
    "title": "Adidas Samba OG 复古德训鞋真假对比与上脚穿搭！值不值得入手？",
    "description": "全方位剖析皮质鞋面、烫金Logo、鞋底抓地力与日常百搭穿搭示范。",
    "platform": "douyin",
    "platform_name": "Douyin (抖音)",
    "region": "china",
    "author": "球鞋老玩家",
    "author_avatar": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80",
    "view_count": "1,420,000",
    "view_count_raw": 1420000,
    "duration": "02:40",
    "publish_date": "2026-09-12",
    "match_score": 92,
    "thumbnail_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.douyin.com/video/728193021",
    "category": "Fashion",
    "keywords": [
      "adidas",
      "samba",
      "sneakers",
      "shoes",
      "รองเท้า",
      "รองเท้าผ้าใบ",
      "板鞋",
      "穿搭"
    ]
  },
  {
    "id": "ks-toy-01",
    "title": "POP MART Labubu 拉布布盲盒拆盒实录！隐藏款竟然被我抽中了？",
    "description": "拆箱整盒泡泡玛特盲盒，展示细节做工、防伪标识与隐藏款概率分析。",
    "platform": "kuaishou",
    "platform_name": "Kuaishou (快手)",
    "region": "china",
    "author": "潮玩拆盒王",
    "author_avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
    "view_count": "920,000",
    "view_count_raw": 920000,
    "duration": "04:10",
    "publish_date": "2026-09-25",
    "match_score": 91,
    "thumbnail_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.kuaishou.com/short-video/3x89a",
    "category": "Toys",
    "keywords": [
      "labubu",
      "popmart",
      "blindbox",
      "ลาบูบู้",
      "กล่องสุ่ม",
      "ของเล่น",
      "盲盒",
      "潮玩"
    ]
  },
  {
    "id": "yt-tech-01",
    "title": "iPhone 16 Pro Max Review: The Truth After 30 Days! (Camera vs Galaxy S24 Ultra)",
    "description": "Comprehensive review of iPhone 16 Pro Max, testing the new Camera Control button, 4K 120fps video, A18 Pro benchmark, and battery endurance.",
    "platform": "youtube",
    "platform_name": "YouTube",
    "region": "international",
    "author": "Marques Brownlee (MKBHD)",
    "author_avatar": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80",
    "view_count": "6,780,000",
    "view_count_raw": 6780000,
    "duration": "21:10",
    "publish_date": "2026-09-22",
    "match_score": 99,
    "thumbnail_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.youtube.com/watch?v=MKBHDiPhone16",
    "category": "Electronics",
    "keywords": [
      "iphone",
      "iphone 16",
      "apple",
      "smartphone",
      "โทรศัพท์",
      "ไอโฟน",
      "มือถือ",
      "mkbhd",
      "review"
    ]
  },
  {
    "id": "yt-home-01",
    "title": "Dyson Airwrap Multi-Styler Complete Long Real Test: Is It Worth $600?",
    "description": "Watch full tutorial and performance test of Dyson Airwrap on curly and straight hair types. Heat damage test included.",
    "platform": "youtube",
    "platform_name": "YouTube",
    "region": "international",
    "author": "Beauty Within",
    "author_avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    "view_count": "4,120,000",
    "view_count_raw": 4120000,
    "duration": "14:30",
    "publish_date": "2026-07-18",
    "match_score": 96,
    "thumbnail_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.youtube.com/watch?v=DysonAirwrapTest",
    "category": "Beauty",
    "keywords": [
      "dyson",
      "airwrap",
      "hair dryer",
      "ไดร์เป่าผม",
      "ทำผม",
      "เครื่องม้วนผม",
      "styler"
    ]
  },
  {
    "id": "tt-shoes-01",
    "title": "Nike Air Jordan 1 Retro High OG Unboxing & On-Foot Review #sneakerhead",
    "description": "Detailed look at leather quality, sizing tips, laced up styling, and comfort test after walking all day.",
    "platform": "tiktok",
    "platform_name": "TikTok",
    "region": "international",
    "author": "@KickTalks",
    "author_avatar": "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&auto=format&fit=crop&q=80",
    "view_count": "5,300,000",
    "view_count_raw": 5300000,
    "duration": "01:00",
    "publish_date": "2026-09-15",
    "match_score": 97,
    "thumbnail_url": "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.tiktok.com/@KickTalks/video/7391823",
    "category": "Fashion",
    "keywords": [
      "nike",
      "jordan",
      "jordan 1",
      "sneakers",
      "shoes",
      "รองเท้า",
      "ไนกี้",
      "รองเท้าผ้าใบ"
    ]
  },
  {
    "id": "yt-gaming-01",
    "title": "Nintendo Switch OLED Model 2 Years Later: Still Worth Buying in 2026?",
    "description": "Comprehensive long term review of the OLED display, battery life degradation, Joy-Con drift status, and top exclusive game performance.",
    "platform": "youtube",
    "platform_name": "YouTube",
    "region": "international",
    "author": "Spawn Wave",
    "author_avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    "view_count": "1,650,000",
    "view_count_raw": 1650000,
    "duration": "16:20",
    "publish_date": "2026-08-04",
    "match_score": 94,
    "thumbnail_url": "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.youtube.com/watch?v=SwitchOLEDReview",
    "category": "Gaming",
    "keywords": [
      "nintendo",
      "switch",
      "nintendo switch",
      "oled",
      "gaming",
      "เกม",
      "เครื่องเกม"
    ]
  },
  {
    "id": "ig-fashion-01",
    "title": "Gentle Monster Sunglasses Collection 2026 Try-On & Face Shape Guide",
    "description": "Testing popular frames on round, oval and square face shapes. UV protection rating and case quality review.",
    "platform": "instagram",
    "platform_name": "Instagram Reels",
    "region": "international",
    "author": "@StyleWithSarah",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    "view_count": "890,000",
    "view_count_raw": 890000,
    "duration": "00:45",
    "publish_date": "2026-09-19",
    "match_score": 90,
    "thumbnail_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.instagram.com/reel/C8921xa",
    "category": "Fashion",
    "keywords": [
      "gentle monster",
      "sunglasses",
      "glasses",
      "แว่นตา",
      "แว่นกันแดด",
      "แฟชั่น"
    ]
  },
  {
    "id": "yt-coffee-01",
    "title": "Nespresso Vertuo Pop Machine Review: Best Budget Espresso Maker?",
    "description": "Testing crema quality, capsule costs, milk frother compatibility, cleaning process, and 6 month durability.",
    "platform": "youtube",
    "platform_name": "YouTube",
    "region": "international",
    "author": "James Hoffmann",
    "author_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    "view_count": "2,890,000",
    "view_count_raw": 2890000,
    "duration": "12:05",
    "publish_date": "2026-06-30",
    "match_score": 93,
    "thumbnail_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
    "embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "source_url": "https://www.youtube.com/watch?v=NespressoVertuoReview",
    "category": "Home",
    "keywords": [
      "nespresso",
      "coffee",
      "espresso",
      "กาแฟ",
      "เครื่องชงกาแฟ",
      "แคปซูล"
    ]
  }
];

window.PLATFORM_METADATA = {
  "bilibili": {
    "name": "Bilibili (哔哩哔哩)",
    "region": "china",
    "icon": "📺",
    "color": "#fb7299",
    "badge_bg": "rgba(251, 114, 153, 0.15)",
    "badge_text": "#ff6699"
  },
  "douyin": {
    "name": "Douyin (抖音)",
    "region": "china",
    "icon": "🎵",
    "color": "#fe2c55",
    "badge_bg": "rgba(254, 44, 85, 0.15)",
    "badge_text": "#ff3b5c"
  },
  "xiaohongshu": {
    "name": "Xiaohongshu (小红书)",
    "region": "china",
    "icon": "📕",
    "color": "#ff2442",
    "badge_bg": "rgba(255, 36, 66, 0.15)",
    "badge_text": "#ff3855"
  },
  "kuaishou": {
    "name": "Kuaishou (快手)",
    "region": "china",
    "icon": "📹",
    "color": "#ff5000",
    "badge_bg": "rgba(255, 80, 0, 0.15)",
    "badge_text": "#ff6600"
  },
  "youtube": {
    "name": "YouTube",
    "region": "international",
    "icon": "▶️",
    "color": "#ff0000",
    "badge_bg": "rgba(255, 0, 0, 0.15)",
    "badge_text": "#ff4d4d"
  },
  "tiktok": {
    "name": "TikTok",
    "region": "international",
    "icon": "📱",
    "color": "#00f2fe",
    "badge_bg": "rgba(0, 242, 254, 0.15)",
    "badge_text": "#00d2fe"
  },
  "instagram": {
    "name": "Instagram Reels",
    "region": "international",
    "icon": "📸",
    "color": "#e1306c",
    "badge_bg": "rgba(225, 48, 108, 0.15)",
    "badge_text": "#f56040"
  }
};
